correction erreur multiple

diff --git a/ResPinGuy-File/respinguy-build b/ResPinGuy-File/respinguy-build
--- a/ResPinGuy-File/respinguy-build
+++ b/ResPinGuy-File/respinguy-build
@@ -1,150 +1,120 @@
 #!/bin/bash
-#_____________________________________________________________________________________________
-# Seul root peut continuer, car seul root peut lire tous les fichiers de votre système !
-#
-allow_only_root()
-{
-  if [ "0$UID" -ne 0 ]; then
-     echo "Merci d'être en root pour lancer : $(basename $0)"; exit 1
-  fi
+allow_only_root() {
+  if [ "0$UID" -ne 0 ]; then echo "Merci d'être en root pour lancer : $(basename $0)"; exit 1; fi
 }
 allow_only_root
-#
-cd /usr/share/ResPinGuy-File-Config/
+
+cd /usr/share/ResPinGuy-File-Config/ || exit 1
 . ./respinguy-config || exit 1
-#
-#######################################################################
-# Vérification les dependences
+
 bash /usr/share/ResPinGuy-File/respinguy-app-dep
-#######################################################################
-if [ ! $(dracut --list-modules | grep squash) ]; then
-   clear
-   echo "Impossible de trouver le module : squash"
-   echo "Vous pouvez envisager d'installer le package contenant le module."
-   echo "Généralement le package s'appel : dracut-squash"
-	exit 1
+if [ $? -ne 0 ]; then echo "[ERREUR] Dépendances manquantes. Build annulé."; exit 1; fi
+
+if [ ! "$(dracut --list-modules | grep squash)" ]; then
+  echo "[ERREUR] Module dracut manquant : squash (package : dracut-squash)"; exit 1
 fi
-if [ ! $(dracut --list-modules | grep dmsquash-live) ]; then
-   clear
-   echo "Impossible de trouver le module : dmsquash-live"
-   echo "Vous pouvez envisager d'installer le package contenant le module."
-   echo "Généralement le package s'appel : dracut-live"
-	exit 1
+if [ ! "$(dracut --list-modules | grep dmsquash-live)" ]; then
+  echo "[ERREUR] Module dracut manquant : dmsquash-live (package : dracut-live)"; exit 1
 fi
-#_____________________________________________________________________________________________
+if [ ! -f "$VMLINUZ" ]; then
+  echo "[ERREUR] Kernel introuvable : $VMLINUZ"; exit 1
+fi
+if [ -z "$RPGBUILDNAME" ] || [ -z "$RPGHOME" ] || [ -z "$KERNEL" ]; then
+  echo "[ERREUR] Variable RPGBUILDNAME, RPGHOME ou KERNEL non définie dans respinguy-config"; exit 1
+fi
+if [ -n "$RPGCONFIGUSER" ] && [ -n "$RPGCONFIGUSERPERS" ]; then
+  echo "[ERREUR] RPGCONFIGUSER et RPGCONFIGUSERPERS ne peuvent pas être définis en même temps."; exit 1
+fi
+
 clear
 echo "_ _ _"
-echo "Résumer avant création"
+echo "Résumé avant création"
 echo "---"
-echo "Nom : "$RPGBUILDNAME""
-echo "Emplacement Kernel : "$VMLINUZ""
-echo "Emplacement initramfs : "$INITRD""
-echo "Kernel Version : "$KERNEL""
-echo "Architecture : "$ARCH""
-echo "Extension du squashfs : "$SQEX""
-echo "Dossier copier a partir de / : "$ROOTDIR""
-echo "Dossier de l'ISO final : "$RPGHOME""
-echo "Tout sera créer dans : /respinguy-build-dir/"
-echo "_ _ _"
-if [[ -n "$RPGCONFIGUSER" && -n "$RPGCONFIGUSERPERS" ]]; then
-  clear
-  echo "Erreur : Les variables RPGCONFIGUSER et RPGCONFIGUSERPERS ne peuvent pas être définies en même temps."
-  exit 1
-fi
-echo "OK : RPGCONFIGUSER et RPGCONFIGUSERPERS ne sont pas en conflit"
-if [ -n "$HOME" ] && [ -n "$RPGCONFIGUSER" ]; then
-    echo "Le répertoire $HOME sera utilisé comme config pour tous les nouveaux utilisateurs"
-    echo "Uniquement dans l'ISO"
+echo "Nom              : $RPGBUILDNAME"
+echo "Kernel           : $VMLINUZ"
+echo "Version kernel   : $KERNEL"
+echo "Architecture     : $ARCH"
+echo "Dossiers inclus  : $ROOTDIR"
+echo "ISO de sortie    : $RPGHOME"
+echo "Dossier de build : /respinguy-build-dir/"
+if [ -n "$RPGCONFIGUSER" ]; then
+  echo "Home utilisateur : $HOME (ISO uniquement)"
+elif [ -n "$RPGCONFIGUSERPERS" ]; then
+  echo "Home utilisateur : $HOME (ISO + persistance)"
 else
-    echo "Le répertoire $HOME ne sera pas utilisé comme config pour tous les nouveaux utilisateurs"
-    echo "Même dans l'ISO"
-fi
-if [ -n "$HOME" ] && [ -n "$RPGCONFIGUSERPERS" ]; then
-    echo "Le répertoire $HOME sera utilisé comme config pour tous les nouveaux utilisateurs"
-    echo "Dans l'ISO et sur le système actuel !"
-else
-    echo "Le répertoire $HOME ne sera pas utilisé comme config pour tous les nouveaux utilisateurs"
-    echo "Même dans l'ISO"
+  echo "Home utilisateur : non inclus"
 fi
 echo "_ _ _"
-echo "Nettoyage de /respinguy-build-dir/ ..."
 rm -rf /respinguy-build-dir/
-read -p "Appuyez sur une touche pour continuer ..."
-#
-#_________________________________________________
-#
-cd /
-echo "Préparation de /respinguy-build-dir/LiveOS ..."
+read -p "Appuyez sur Entrée pour lancer le build..."
+
+cd / || exit 1
 mkdir -p /respinguy-build-dir/LiveOS
-echo "Terminé"
-echo "_ _ _"
-echo "Copie des fichiers de configuration ..."
-echo "."
+
+echo "Copie des fichiers ISO..."
 cp -r /usr/share/ResPinGuy-File/fichier/iso/isolinux/ /respinguy-build-dir/
-echo "."
 cp /usr/share/ResPinGuy-File-Config/bootimg.png /respinguy-build-dir/isolinux/
-echo "."
 cp /usr/share/ResPinGuy-File-Config/isolinux.cfg /respinguy-build-dir/isolinux/
-echo "Terminé"
-echo "_ _ _"
-echo "Création de $RPGHOME ..."
-rm -r $RPGHOME
-mkdir $RPGHOME
-echo "Terminé"
-echo "_ _ _"
-echo "Copie de $VMLINUZ ..."
-cp $VMLINUZ /respinguy-build-dir/vmlinuz
-##########################################################################################################################################################
-echo "Terminé"
-read -p "Appuyez sur une touche pour continuer ..."
-clear
-#
-if [ $RPGCONFIGUSER ]; then
-    $RPGCONFIGUSER
-    RPGCONFIGUSERRM= sh ./usr/share/ResPinGuy-File/script/rcurm
-    echo "OK : RPGCONFIGUSER"
-elif [ $RPGCONFIGUSERPERS ]; then
-    $RPGCONFIGUSERPERS
-    echo "OK : RPGCONFIGUSERPERS"
+
+if [ -n "$RPGHOME" ] && [ "$RPGHOME" != "/" ]; then
+  rm -rf "$RPGHOME" && mkdir -p "$RPGHOME"
 else
-    echo "Le répertoire $HOME ne sera aucunement utilisé comme config pour tous les nouveaux utilisateurs"
+  echo "[ERREUR] RPGHOME invalide : '$RPGHOME'"; exit 1
 fi
-#
-#_____________________________________________________________________________________________
-# Création de l'image squashfs :
-echo "Création du squashfs 0/1 ..."
+
+echo "Copie du kernel..."
+cp "$VMLINUZ" /respinguy-build-dir/vmlinuz
+
+read -p "Appuyez sur Entrée pour continuer..."
+clear
+
+if [ -n "$RPGCONFIGUSER" ]; then
+  bash /usr/share/ResPinGuy-File/script/rcu
+elif [ -n "$RPGCONFIGUSERPERS" ]; then
+  bash /usr/share/ResPinGuy-File/script/rcup
+fi
+
+echo "Création du squashfs..."
 SQSFDIR=""
 for i in $ROOTDIR; do
-   if [ -d /$i ]; then
-      SQSFDIR="$SQSFDIR /$i"
-   fi
+  [ -d "/$i" ] && SQSFDIR="$SQSFDIR /$i"
 done
-mksquashfs $SQSFDIR /respinguy-build-dir/LiveOS/squashfs.img -comp xz -b 1024K -always-use-fragments -keep-as-directory $CLEANCACHE
-clear
-echo "Création du squashfs 1/1 ..."
-read -p "Appuyez sur une touche pour continuer ..."
-echo "Création de l'initrd ..."
-if [ "$RPGCONFIGUSER" ]; then
-    # Action à exécuter si $RPGCONFIGUSER est vrai (non vide)
-    $RPGCONFIGUSERRM
+if [ -z "$SQSFDIR" ]; then echo "[ERREUR] Aucun dossier valide dans ROOTDIR."; exit 1; fi
+
+mksquashfs $SQSFDIR /respinguy-build-dir/LiveOS/squashfs.img \
+  -comp xz -b 1024K -always-use-fragments -keep-as-directory -noappend \
+  -wildcards \
+  -e "proc/*" "proc/.*" "run/*" "run/.*" "tmp/*" "tmp/.*" "sys/*" "sys/.*" \
+  -e "var/crash/*" "root/.bash_history" "root/.cache" "root/.wget-hsts" \
+  -e "home/*/.bash_history" "home/*/.cache" "home/*/.wget-hsts"
+
+if [ $? -ne 0 ]; then echo "[ERREUR] Échec de la création du squashfs."; exit 1; fi
+echo "Squashfs créé."
+read -p "Appuyez sur Entrée pour continuer..."
+
+if [ -n "$RPGCONFIGUSER" ]; then
+  bash /usr/share/ResPinGuy-File/script/rcurm
 fi
-# ( PROBLEME A LA CREATION DE L'INITRD !!! )
-#
-dracut -N -a dmsquash-live --add-fstab /usr/share/ResPinGuy-File-Config/fstab /respinguy-build-dir/initrd --force
-#dracut -N -a dmsquash-live /respinguy-build-dir/initrd --force
-#
-#dracut -N -a dmsquash-live --conf /usr/share/ResPinguy-File-Config/dracut.conf /respinguy-build-dir/initrd --force
-#dracut -N -a dmsquash-live  --filesystems "squashfs" /respinguy-build-dir/initrd --force
-# --filesystems "squashfs"
-#
-read -p "Appuyez sur une touche pour continuer ..."
-#_____________________________________________________________________________________________
-#Script Build
-cd /
-xorriso -as mkisofs -r -J -joliet-long -l -iso-level 3 -cache-inodes -isohybrid-mbr /usr/share/ResPinGuy-File/fichier/isohdpfx.bin -partition_offset 16 -A "$RPGBUILDNAME"  -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o $RPGHOME/$RPGBUILDNAME-$ARCH.iso /respinguy-build-dir/
+
+echo "Création de l'initrd..."
+dracut -N -a dmsquash-live --kver "$KERNEL" /respinguy-build-dir/initrd --force
+if [ $? -ne 0 ]; then echo "[ERREUR] Échec de la création de l'initrd."; exit 1; fi
+echo "initrd créé."
+read -p "Appuyez sur Entrée pour continuer..."
+
+echo "Création de l'image ISO..."
+cd / || exit 1
+xorriso -as mkisofs \
+  -r -J -joliet-long -l -iso-level 3 -cache-inodes \
+  -isohybrid-mbr /usr/share/ResPinGuy-File/fichier/isohdpfx.bin \
+  -partition_offset 16 -A "$RPGBUILDNAME" \
+  -b isolinux/isolinux.bin -c isolinux/boot.cat \
+  -no-emul-boot -boot-load-size 4 -boot-info-table \
+  -o "$RPGHOME/$RPGBUILDNAME-$ARCH.iso" \
+  /respinguy-build-dir/
+
+if [ $? -ne 0 ]; then echo "[ERREUR] Échec de la création de l'ISO."; exit 1; fi
 clear
 echo "_ _ _"
-echo "Terminé. vous pourez votre résultat dans $RPGHOME"
+echo "Build terminé ! ISO disponible dans : $RPGHOME/$RPGBUILDNAME-$ARCH.iso"
 echo "_ _ _"
-# rm -rf /respinguy-build-dir/*
-#_____________________________________________________________________________________________
